image: archlinux

environment:
  PGHOST: localhost
  PGDATABASE: app
  PGUSERNAME: grokloc
  PGPASSWORD: grokloc

tasks:
  - update-pacman: |
      sudo pacman -Sy
  - update-packages: |
      sudo pacman --noconfirm -S just fish postgresql
  - init-postgres: |
      cd /home/build/grokloc-db && sudo just initdb
      sudo systemctl start postgresql.service && sleep 5
  - test: |
      cd /home/build/grokloc-db && just create-users create-databases alter-grants apply-schema
