name: CI

on: 
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-24.04
    env:
      PGHOST: localhost
      PGDATABASE: app
      PGUSERNAME: grokloc
      PGPASSWORD: grokloc
    steps:
      - uses: actions/checkout@v4
      - name: update
        run: |
          sudo apt update
      - name: install deps
        run: |
          sudo apt install -y just fish
      - name: initialize db
        run: |
          sudo systemctl start postgresql.service && sleep 3
          just create-users create-databases alter-grants apply-schema
     
